<a href="https://colab.research.google.com/github/shan9193/Personal-finance-advisor-using-ML/blob/Today's-work/Personal_finance_advisor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
url = "https://raw.githubusercontent.com/shan9193/Personal-finance-advisor-using-ML/refs/heads/main/data.csv"
df = pd.read_csv(url)

In [4]:
df.shape

(20000, 27)

In [5]:
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
0,44637.249636,49,0,Self_Employed,Tier_1,13391.174891,0.000000,2206.490129,6658.768341,2636.970696,...,6200.537192,11265.627707,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517
1,26858.596592,34,2,Retired,Tier_2,5371.719318,0.000000,869.522617,2818.444460,1543.018778,...,1923.176434,9676.818733,540.306561,119.347139,141.866089,234.131168,286.668408,6.603212,56.306874,97.388606
2,50367.605084,35,1,Student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,7050.360422,13891.450624,1466.073984,473.549752,410.857129,459.965256,488.383423,7.290892,106.653597,138.542422
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,16694.965136,31617.953615,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183
4,24875.283548,52,4,Professional,Tier_2,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,1874.099434,6265.700532,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           20000 non-null  float64
 1   Age                              20000 non-null  int64
 2   Dependents                       20000 non-null  int64
 3   Occupation                       20000 non-null  object
 4   City_Tier                        20000 non-null  object
 5   Rent                             20000 non-null  float64
 6   Loan_Repayment                   20000 non-null  float64
 7   Insurance                        20000 non-null  float64
 8   Groceries                        20000 non-null  float64
 9   Transport                        20000 non-null  float64
 10  Eating_Out                       20000 non-null  float64
 11  Entertainment                    20000 non-null  float64
 12  Utilities                        20000 non-null  float64
 13  Healthcare                       20000 non-null  float64
 14  Education                        20000 non-null  float64
 15  Miscellaneous                    20000 non-null  float64
 16  Desired_Savings_Percentage       20000 non-null  float64
 17  Desired_Savings                  20000 non-null  float64
 18  Disposable_Income                20000 non-null  float64
 19  Potential_Savings_Groceries      20000 non-null  float64
 20  Potential_Savings_Transport      20000 non-null  float64
 21  Potential_Savings_Eating_Out     20000 non-null  float64
 22  Potential_Savings_Entertainment  20000 non-null  float64
 23  Potential_Savings_Utilities      20000 non-null  float64
 24  Potential_Savings_Healthcare     20000 non-null  float64
 25  Potential_Savings_Education      20000 non-null  float64
 26  Potential_Savings_Miscellaneous  20000 non-null  float64
dtypes: float64(23), int64(2), object(2)
memory usage: 4.1+ MB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Income,20000.0,41585.496104,40014.540538,1301.187333,17604.875957,30185.383480,51765.446460,1.079728e+06
Age,20000.0,41.031450,13.578725,18.000000,29.000000,41.000000,53.000000,6.400000e+01
Dependents,20000.0,1.995950,1.417616,0.000000,1.000000,2.000000,3.000000,4.000000e+00
Rent,20000.0,9115.494629,9254.228188,235.365692,3649.422246,6402.751824,11263.940492,2.159457e+05
Loan_Repayment,20000.0,2049.800292,4281.789941,0.000000,0.000000,0.000000,2627.142320,1.230807e+05
Insurance,20000.0,1455.028761,1492.938435,30.002012,580.204749,1017.124681,1787.160895,3.873493e+04
Groceries,20000.0,5205.667493,5035.953689,154.078240,2165.426419,3741.091535,6470.892718,1.198169e+05
Transport,20000.0,2704.466685,2666.345648,81.228584,1124.578012,1933.845509,3360.597508,8.186150e+04
Eating_Out,20000.0,1461.856982,1481.660811,39.437523,581.011801,1029.109726,1807.075251,3.440610e+04
Entertainment,20000.0,1448.853658,1489.019270,45.421469,581.632906,1020.198376,1790.104082,3.866737e+04
Utilities,20000.0,2504.976953,2522.981880,75.429414,1017.670366,1766.474869,3103.723308,5.372544e+04
Healthcare,20000.0,1663.081794,1628.163024,53.500761,684.364440,1189.203827,2057.082277,3.600153e+04
Education,20000.0,2498.348422,3098.438166,0.000000,611.682170,1701.901075,3311.705122,8.166509e+04
Miscellaneous,20000.0,830.553181,845.019922,20.503223,323.626896,579.078393,1025.195018,1.585636e+04
Desired_Savings_Percentage,20000.0,9.804183,3.903858,5.000042,6.940423,8.898622,11.877171,2.499878e+01
Desired_Savings,20000.0,4982.878416,7733.468188,0.000000,1224.932636,2155.356763,6216.309609,2.455045e+05
Disposable_Income,20000.0,10647.367257,11740.637289,-5400.788673,3774.894323,7224.890977,13331.950716,3.770602e+05
Potential_Savings_Groceries,20000.0,912.197183,1038.884968,16.575501,317.811000,607.038735,1128.681837,3.489464e+04
Potential_Savings_Transport,20000.0,473.042650,537.222853,8.268076,161.913751,307.045856,588.419602,1.227326e+04
Potential_Savings_Eating_Out,20000.0,254.963280,296.047943,3.797926,84.506870,164.927660,313.398240,5.573036e+03
Potential_Savings_Entertainment,20000.0,254.031058,299.973590,3.121610,84.562090,164.740232,310.927935,6.222201e+03
Potential_Savings_Utilities,20000.0,436.332808,503.200658,6.200297,148.013618,285.739582,538.983703,8.081800e+03
Potential_Savings_Healthcare,20000.0,41.524964,53.152458,0.001238,11.037421,25.202124,52.353736,1.394531e+03
Potential_Savings_Education,20000.0,62.417083,98.842656,0.000000,4.926210,33.127987,80.946145,3.647244e+03
Potential_Savings_Miscellaneous,20000.0,144.904987,169.160951,2.091973,47.637307,93.090257,178.257981,4.637951e+03

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.corr(numeric_only = True)

,Income,Age,Dependents,Rent,Loan_Repayment,Insurance,Groceries,Transport,Eating_Out,Entertainment,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
Income,1.000000,-0.005201,0.016926,0.939370,0.447598,0.944395,0.985717,0.981955,0.939673,0.943594,...,0.944510,0.881518,0.851086,0.838267,0.799650,0.812415,0.832575,0.768083,0.646553,0.805790
Age,-0.005201,1.000000,-0.011342,-0.007258,-0.000737,-0.002321,-0.004604,-0.006702,-0.005207,-0.003771,...,-0.005363,-0.002634,-0.008521,-0.006494,-0.004979,0.000539,-0.006346,-0.005591,-0.009966,-0.013153
Dependents,0.016926,-0.011342,1.000000,0.018390,-0.002468,0.018162,0.016375,0.015371,0.015744,0.015720,...,0.009293,-0.059502,0.021444,0.019211,0.009970,0.010645,0.012556,0.014607,0.237070,0.016267
Rent,0.939370,-0.007258,0.018390,1.000000,0.419682,0.894195,0.926205,0.922790,0.878156,0.885604,...,0.858403,0.732520,0.795361,0.796904,0.745848,0.765975,0.789790,0.719458,0.610576,0.753787
Loan_Repayment,0.447598,-0.000737,-0.002468,0.419682,1.000000,0.429958,0.438350,0.433747,0.413322,0.425665,...,0.311471,0.106274,0.368029,0.398728,0.339241,0.378230,0.363552,0.339905,0.284429,0.371172
Insurance,0.944395,-0.002321,0.018162,0.894195,0.429958,1.000000,0.928354,0.927134,0.882410,0.890283,...,0.886320,0.810917,0.797137,0.791154,0.753159,0.767430,0.779164,0.715983,0.618554,0.764189
Groceries,0.985717,-0.004604,0.016375,0.926205,0.438350,0.928354,1.000000,0.967789,0.929536,0.931417,...,0.925797,0.858575,0.861040,0.827819,0.793967,0.800435,0.820303,0.757205,0.628757,0.793543
Transport,0.981955,-0.006702,0.015371,0.922790,0.433747,0.927134,0.967789,1.000000,0.920028,0.926108,...,0.927854,0.861517,0.835439,0.851187,0.781004,0.795654,0.816511,0.756648,0.635145,0.798308
Eating_Out,0.939673,-0.005207,0.015744,0.878156,0.413322,0.882410,0.929536,0.920028,1.000000,0.889231,...,0.883868,0.820923,0.803760,0.785348,0.860961,0.769658,0.787147,0.721393,0.591749,0.746478
Entertainment,0.943594,-0.003771,0.015720,0.885604,0.425665,0.890283,0.931417,0.926108,0.889231,1.000000,...,0.887401,0.816446,0.803879,0.793985,0.753366,0.864139,0.778574,0.731614,0.611686,0.758614
Utilities,0.964414,-0.004182,0.016835,0.905489,0.438967,0.909922,0.950489,0.945710,0.910472,0.908553,...,0.905287,0.833621,0.820529,0.811118,0.778832,0.788442,0.860647,0.736473,0.612309,0.772638
Healthcare,0.978838,-0.006485,0.013618,0.920814,0.438034,0.921213,0.964956,0.960117,0.922030,0.924304,...,0.922190,0.856866,0.833337,0.820949,0.788767,0.799574,0.818044,0.782427,0.624251,0.790959
Education,0.794558,-0.007129,0.301412,0.755500,0.344756,0.757517,0.779126,0.776084,0.736662,0.751592,...,0.735237,0.603028,0.678846,0.664606,0.625503,0.648975,0.656730,0.606594,0.805127,0.644141
Miscellaneous,0.919519,-0.006909,0.024156,0.867142,0.421336,0.871969,0.905033,0.899992,0.861328,0.866449,...,0.861215,0.791300,0.781462,0.778220,0.726167,0.753912,0.764585,0.703732,0.608048,0.865292
Desired_Savings_Percentage,0.776295,0.002147,0.014610,0.732829,0.347200,0.731176,0.770719,0.758924,0.739919,0.724432,...,0.789808,0.681183,0.655422,0.660163,0.636725,0.630749,0.644952,0.583166,0.476049,0.628004
Desired_Savings,0.944510,-0.005363,0.009293,0.858403,0.311471,0.886320,0.925797,0.927854,0.883868,0.887401,...,1.000000,0.905816,0.802843,0.782045,0.752011,0.762206,0.784007,0.724214,0.608130,0.755980
Disposable_Income,0.881518,-0.002634,-0.059502,0.732520,0.106274,0.810917,0.858575,0.861517,0.820923,0.816446,...,0.905816,1.000000,0.748437,0.715082,0.701770,0.692994,0.721287,0.677729,0.499345,0.699522
Potential_Savings_Groceries,0.851086,-0.008521,0.021444,0.795361,0.368029,0.797137,0.861040,0.835439,0.803760,0.803879,...,0.802843,0.748437,1.000000,0.701967,0.677571,0.677674,0.693161,0.657173,0.568170,0.688938
Potential_Savings_Transport,0.838267,-0.006494,0.019211,0.796904,0.398728,0.791154,0.827819,0.851187,0.785348,0.793985,...,0.782045,0.715082,0.701967,1.000000,0.682852,0.698677,0.695522,0.638522,0.538515,0.676872
Potential_Savings_Eating_Out,0.799650,-0.004979,0.009970,0.745848,0.339241,0.753159,0.793967,0.781004,0.860961,0.753366,...,0.752011,0.701770,0.677571,0.682852,1.000000,0.653237,0.684294,0.613681,0.490472,0.627958
Potential_Savings_Entertainment,0.812415,0.000539,0.010645,0.765975,0.378230,0.767430,0.800435,0.795654,0.769658,0.864139,...,0.762206,0.692994,0.677674,0.698677,0.653237,1.000000,0.675444,0.615932,0.526644,0.658428
Potential_Savings_Utilities,0.832575,-0.006346,0.012556,0.789790,0.363552,0.779164,0.820303,0.816511,0.787147,0.778574,...,0.784007,0.721287,0.693161,0.695522,0.684294,0.675444,1.000000,0.636389,0.520859,0.662417
Potential_Savings_Healthcare,0.768083,-0.005591,0.014607,0.719458,0.339905,0.715983,0.757205,0.756648,0.721393,0.731614,...,0.724214,0.677729,0.657173,0.638522,0.613681,0.615932,0.636389,1.000000,0.496861,0.622926
Potential_Savings_Education,0.646553,-0.009966,0.237070,0.610576,0.284429,0.618554,0.628757,0.635145,0.591749,0.611686,...,0.608130,0.499345,0.568170,0.538515,0.490472,0.526644,0.520859,0.496861,1.000000,0.534225
Potential_Savings_Miscellaneous,0.805790,-0.013153,0.016267,0.753787,0.371172,0.764189,0.793543,0.798308,0.746478,0.758614,...,0.755980,0.699522,0.688938,0.676872,0.627958,0.658428,0.662417,0.622926,0.534225,1.000000

In [10]:
df.columns

Index(['Income', 'Age', 'Dependents', 'Occupation', 'City_Tier', 'Rent',
       'Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out',
       'Entertainment', 'Utilities', 'Healthcare', 'Education',
       'Miscellaneous', 'Desired_Savings_Percentage', 'Desired_Savings',
       'Disposable_Income', 'Potential_Savings_Groceries',
       'Potential_Savings_Transport', 'Potential_Savings_Eating_Out',
       'Potential_Savings_Entertainment', 'Potential_Savings_Utilities',
       'Potential_Savings_Healthcare', 'Potential_Savings_Education',
       'Potential_Savings_Miscellaneous'],
      dtype='object')

In [11]:
df['Achieved_Goal'] = np.where((df['Income']-df[['Rent',
       'Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out',
       'Entertainment', 'Utilities', 'Healthcare', 'Education',
       'Miscellaneous']].sum(axis=1) >= df['Disposable_Income']), 1, 0)
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous,Achieved_Goal
0,44637.249636,49,0,Self_Employed,Tier_1,13391.174891,0.000000,2206.490129,6658.768341,2636.970696,...,11265.627707,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517,1
1,26858.596592,34,2,Retired,Tier_2,5371.719318,0.000000,869.522617,2818.444460,1543.018778,...,9676.818733,540.306561,119.347139,141.866089,234.131168,286.668408,6.603212,56.306874,97.388606,1
2,50367.605084,35,1,Student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,13891.450624,1466.073984,473.549752,410.857129,459.965256,488.383423,7.290892,106.653597,138.542422,1
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,31617.953615,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183,0
4,24875.283548,52,4,Professional,Tier_2,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,6265.700532,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076,1

In [12]:
df['Achieved_Goal'].value_counts()

Achieved_Goal
1    16141
0     3859
Name: count, dtype: int64

In [13]:
df.columns.get_loc('Disposable_Income')

18

In [14]:
df.insert(19, 'Saving_Rate', df['Disposable_Income']/df['Income'])
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Saving_Rate,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous,Achieved_Goal
0,44637.249636,49,0,Self_Employed,Tier_1,13391.174891,0.000000,2206.490129,6658.768341,2636.970696,...,0.252382,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517,1
1,26858.596592,34,2,Retired,Tier_2,5371.719318,0.000000,869.522617,2818.444460,1543.018778,...,0.360288,540.306561,119.347139,141.866089,234.131168,286.668408,6.603212,56.306874,97.388606,1
2,50367.605084,35,1,Student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,0.275801,1466.073984,473.549752,410.857129,459.965256,488.383423,7.290892,106.653597,138.542422,1
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,0.311643,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183,0
4,24875.283548,52,4,Professional,Tier_2,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,0.251885,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076,1

In [15]:
df.insert(28, 'Total_Potential_Savinigs', value = df[['Potential_Savings_Groceries',
       'Potential_Savings_Transport', 'Potential_Savings_Eating_Out',
       'Potential_Savings_Entertainment', 'Potential_Savings_Utilities',
       'Potential_Savings_Healthcare', 'Potential_Savings_Education',
       'Potential_Savings_Miscellaneous']].sum(axis = 1))

In [16]:
df.sample(5)

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous,Total_Potential_Savinigs,Achieved_Goal
5174,46569.411997,58,3,Student,Tier_1,13970.823599,8667.046058,1479.542302,6907.120818,3231.048795,...,798.388625,218.352385,234.121366,228.481844,221.367914,37.674473,96.574652,194.600451,2029.561710,1
15509,57838.742176,50,1,Retired,Tier_3,8675.811326,6166.458931,2396.232344,7091.411528,3000.924116,...,371.289176,501.412823,417.129145,644.418934,473.432684,13.042402,76.775056,264.758573,2762.258794,0
6378,61956.511242,25,3,Self_Employed,Tier_1,18586.953373,0.000000,2338.168077,6305.018962,3293.570849,...,1526.765871,902.802088,246.978511,406.493827,613.664586,35.785519,195.968244,284.493033,4212.951680,1
5553,50005.804744,56,4,Self_Employed,Tier_2,10001.160949,3056.757024,1527.972493,5524.235478,3901.982410,...,1272.104137,210.569986,274.556126,91.969485,340.273452,71.991854,50.624133,278.716057,2590.805229,1
9885,12498.415709,34,0,Professional,Tier_3,1874.762356,0.000000,336.463345,1822.008217,792.227049,...,492.072527,87.443994,38.111146,116.625549,46.312108,10.081214,0.000000,40.078945,830.725485,1

In [17]:
new_df = df.drop(df[['Potential_Savings_Groceries',
       'Potential_Savings_Transport', 'Potential_Savings_Eating_Out',
       'Potential_Savings_Entertainment', 'Potential_Savings_Utilities',
       'Potential_Savings_Healthcare', 'Potential_Savings_Education',
       'Potential_Savings_Miscellaneous']], axis=1)

In [18]:
new_df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Utilities,Healthcare,Education,Miscellaneous,Desired_Savings_Percentage,Desired_Savings,Disposable_Income,Saving_Rate,Total_Potential_Savinigs,Achieved_Goal
0,44637.249636,49,0,Self_Employed,Tier_1,13391.174891,0.000000,2206.490129,6658.768341,2636.970696,...,2911.792231,1546.914539,0.000000,831.525120,13.890948,6200.537192,11265.627707,0.252382,3507.222841,1
1,26858.596592,34,2,Retired,Tier_2,5371.719318,0.000000,869.522617,2818.444460,1543.018778,...,1626.143346,1137.351325,1551.723167,564.235007,7.160376,1923.176434,9676.818733,0.360288,1482.618056,1
2,50367.605084,35,1,Student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,3368.457108,2178.515847,3160.026299,628.371220,13.997808,7050.360422,13891.450624,0.275801,3551.316456,1
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,6128.550387,4571.118217,0.000000,2526.055712,16.455440,16694.965136,31617.953615,0.311643,6078.520570,0
4,24875.283548,52,4,Professional,Tier_2,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,1092.689024,1169.095816,1445.215694,515.510300,7.533982,1874.099434,6265.700532,0.251885,1511.357063,1

In [19]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Income                      20000 non-null  float64
 1   Age                         20000 non-null  int64
 2   Dependents                  20000 non-null  int64
 3   Occupation                  20000 non-null  object
 4   City_Tier                   20000 non-null  object
 5   Rent                        20000 non-null  float64
 6   Loan_Repayment              20000 non-null  float64
 7   Insurance                   20000 non-null  float64
 8   Groceries                   20000 non-null  float64
 9   Transport                   20000 non-null  float64
 10  Eating_Out                  20000 non-null  float64
 11  Entertainment               20000 non-null  float64
 12  Utilities                   20000 non-null  float64
 13  Healthcare                  20000 non-null  float64
 14  Education                   20000 non-null  float64
 15  Miscellaneous               20000 non-null  float64
 16  Desired_Savings_Percentage  20000 non-null  float64
 17  Desired_Savings             20000 non-null  float64
 18  Disposable_Income           20000 non-null  float64
 19  Saving_Rate                 20000 non-null  float64
 20  Total_Potential_Savinigs    20000 non-null  float64
 21  Achieved_Goal               20000 non-null  int64
dtypes: float64(17), int64(3), object(2)
memory usage: 3.4+ MB

In [20]:
new_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Income,20000.0,41585.496104,40014.540538,1301.187333,17604.875957,30185.383480,51765.446460,1.079728e+06
Age,20000.0,41.031450,13.578725,18.000000,29.000000,41.000000,53.000000,6.400000e+01
Dependents,20000.0,1.995950,1.417616,0.000000,1.000000,2.000000,3.000000,4.000000e+00
Rent,20000.0,9115.494629,9254.228188,235.365692,3649.422246,6402.751824,11263.940492,2.159457e+05
Loan_Repayment,20000.0,2049.800292,4281.789941,0.000000,0.000000,0.000000,2627.142320,1.230807e+05
Insurance,20000.0,1455.028761,1492.938435,30.002012,580.204749,1017.124681,1787.160895,3.873493e+04
Groceries,20000.0,5205.667493,5035.953689,154.078240,2165.426419,3741.091535,6470.892718,1.198169e+05
Transport,20000.0,2704.466685,2666.345648,81.228584,1124.578012,1933.845509,3360.597508,8.186150e+04
Eating_Out,20000.0,1461.856982,1481.660811,39.437523,581.011801,1029.109726,1807.075251,3.440610e+04
Entertainment,20000.0,1448.853658,1489.019270,45.421469,581.632906,1020.198376,1790.104082,3.866737e+04
Utilities,20000.0,2504.976953,2522.981880,75.429414,1017.670366,1766.474869,3103.723308,5.372544e+04
Healthcare,20000.0,1663.081794,1628.163024,53.500761,684.364440,1189.203827,2057.082277,3.600153e+04
Education,20000.0,2498.348422,3098.438166,0.000000,611.682170,1701.901075,3311.705122,8.166509e+04
Miscellaneous,20000.0,830.553181,845.019922,20.503223,323.626896,579.078393,1025.195018,1.585636e+04
Desired_Savings_Percentage,20000.0,9.804183,3.903858,5.000042,6.940423,8.898622,11.877171,2.499878e+01
Desired_Savings,20000.0,4982.878416,7733.468188,0.000000,1224.932636,2155.356763,6216.309609,2.455045e+05
Disposable_Income,20000.0,10647.367257,11740.637289,-5400.788673,3774.894323,7224.890977,13331.950716,3.770602e+05
Saving_Rate,20000.0,0.255122,0.097190,-0.062378,0.189708,0.264887,0.327676,5.065037e-01
Total_Potential_Savinigs,20000.0,2579.414013,2576.673919,68.118414,1046.514956,1833.535113,3206.461310,6.280116e+04
Achieved_Goal,20000.0,0.807050,0.394624,0.000000,1.000000,1.000000,1.000000,1.000000e+00

In [21]:
new_df.rename(columns={'Total_Potential_Savinigs': 'Total_Potential_Savings'}, inplace=True)

In [22]:
new_df.columns

Index(['Income', 'Age', 'Dependents', 'Occupation', 'City_Tier', 'Rent',
       'Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out',
       'Entertainment', 'Utilities', 'Healthcare', 'Education',
       'Miscellaneous', 'Desired_Savings_Percentage', 'Desired_Savings',
       'Disposable_Income', 'Saving_Rate', 'Total_Potential_Savings',
       'Achieved_Goal'],
      dtype='object')

#Encoding Categorical variables

In [23]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(new_df.drop('Achieved_Goal', axis=1), new_df['Achieved_Goal'], test_size=0.2, random_state=42)

In [61]:
#We will do ordinal encoding for Occupation
oe = OrdinalEncoder(categories=[['Tier_1', 'Tier_2', 'Tier_3']])
oe.fit(X_train[['City_Tier']])

X_train['City_Tier'] = oe.transform(X_train[['City_Tier']])
X_test['City_Tier'] = oe.transform(X_test[['City_Tier']])

ValueError: Found unknown categories ['0.0', '1.0', '2.0'] in column 0 during fit

In [60]:
X_train.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Entertainment,Utilities,Healthcare,Education,Miscellaneous,Desired_Savings_Percentage,Desired_Savings,Disposable_Income,Saving_Rate,Total_Potential_Savings
5894,43033.009737,34,3,Student,1.0,8606.601947,0.000000,1436.722787,5834.519895,3198.182773,...,1410.277931,2334.591458,1577.304427,3784.808282,1164.194464,14.341768,6171.694390,12123.213458,0.281719,2223.371129
3728,11489.566457,19,4,Retired,0.0,3446.869937,2051.213623,410.251969,1685.074536,611.912676,...,483.575046,527.701126,348.067630,588.817424,255.682115,7.287937,697.660941,697.660941,0.060721,831.762200
8958,64302.916006,31,3,Self_Employed,0.0,19290.874802,0.000000,1361.887366,8918.175983,5084.552672,...,2754.933684,4659.413253,2403.603355,3473.275105,1182.368354,14.716779,9463.317967,12213.291235,0.189934,2970.997870
7671,5985.120040,35,3,Self_Employed,2.0,897.768006,308.373725,150.235396,620.098423,358.335042,...,261.670247,302.791292,293.849940,472.610682,155.439767,6.922311,414.308638,1879.544464,0.314036,444.957861
5999,11763.162384,60,1,Professional,1.0,2352.632477,0.000000,325.799958,1757.571252,588.740982,...,475.932118,894.710323,421.720733,1111.439149,255.292653,8.025482,944.050435,3331.198697,0.283189,927.862559

In [64]:
X_train.columns

Index(['Income', 'Age', 'Dependents', 'Occupation', 'City_Tier', 'Rent',
       'Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out',
       'Entertainment', 'Utilities', 'Healthcare', 'Education',
       'Miscellaneous', 'Desired_Savings_Percentage', 'Desired_Savings',
       'Disposable_Income', 'Saving_Rate', 'Total_Potential_Savings'],
      dtype='object')

In [44]:
ohe = OneHotEncoder(sparse_output=False, drop='first')
X_train_new = ohe.fit_transform(X_train[['Occupation']])
X_test_new = ohe.transform(X_test[['Occupation']])

In [68]:
(X_train[['Income', 'Age', 'Dependents', 'Occupation', 'City_Tier', 'Rent',
       'Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out',
       'Entertainment', 'Utilities', 'Healthcare', 'Education',
       'Miscellaneous', 'Desired_Savings_Percentage', 'Desired_Savings',
       'Disposable_Income', 'Saving_Rate', 'Total_Potential_Savings']]).values

array([[43033.00973674387, 34, 3, ..., 12123.213458114877,
        0.2817189300092908, 2223.3711289998455],
       [11489.566457264678, 19, 4, ..., 697.6609409196062,
        0.06072125902352789, 831.7621995701642],
       [64302.91600616403, 31, 3, ..., 12213.291235171018,
        0.18993370742316354, 2970.9978699988137],
       ...,
       [17144.29987505135, 30, 2, ..., 3559.6406395595623,
        0.2076282301116073, 659.9712917874397],
       [35287.74718146083, 32, 1, ..., 6527.1438163160965,
        0.18496912774713117, 1762.3799515665467],
       [25205.778776387164, 55, 4, ..., 5743.78953535495,
        0.2278759004556426, 1660.178948081491]], dtype=object)

In [74]:
X_train_encoded = np.hstack((X_train[['Income', 'Age', 'Dependents', 'Occupation', 'City_Tier', 'Rent','Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out','Entertainment', 'Utilities', 'Healthcare', 'Education','Miscellaneous', 'Desired_Savings_Percentage', 'Desired_Savings','Disposable_Income', 'Saving_Rate', 'Total_Potential_Savings']].values, X_train_new))

In [72]:
X_train.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Entertainment,Utilities,Healthcare,Education,Miscellaneous,Desired_Savings_Percentage,Desired_Savings,Disposable_Income,Saving_Rate,Total_Potential_Savings
5894,43033.009737,34,3,Student,1.0,8606.601947,0.000000,1436.722787,5834.519895,3198.182773,...,1410.277931,2334.591458,1577.304427,3784.808282,1164.194464,14.341768,6171.694390,12123.213458,0.281719,2223.371129
3728,11489.566457,19,4,Retired,0.0,3446.869937,2051.213623,410.251969,1685.074536,611.912676,...,483.575046,527.701126,348.067630,588.817424,255.682115,7.287937,697.660941,697.660941,0.060721,831.762200
8958,64302.916006,31,3,Self_Employed,0.0,19290.874802,0.000000,1361.887366,8918.175983,5084.552672,...,2754.933684,4659.413253,2403.603355,3473.275105,1182.368354,14.716779,9463.317967,12213.291235,0.189934,2970.997870
7671,5985.120040,35,3,Self_Employed,2.0,897.768006,308.373725,150.235396,620.098423,358.335042,...,261.670247,302.791292,293.849940,472.610682,155.439767,6.922311,414.308638,1879.544464,0.314036,444.957861
5999,11763.162384,60,1,Professional,1.0,2352.632477,0.000000,325.799958,1757.571252,588.740982,...,475.932118,894.710323,421.720733,1111.439149,255.292653,8.025482,944.050435,3331.198697,0.283189,927.862559

In [79]:
original_cols = ['Income', 'Age', 'Dependents', 'Occupation', 'City_Tier', 'Rent',
                 'Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out',
                 'Entertainment', 'Utilities', 'Healthcare', 'Education', 'Miscellaneous',
                 'Desired_Savings_Percentage', 'Desired_Savings', 'Disposable_Income',
                 'Saving_Rate', 'Total_Potential_Savings']
encoded_cols = ohe.get_feature_names_out(['Occupation'])
final_column_names = original_cols + encoded_cols.tolist()
odf = pd.DataFrame(X_train_encoded, columns=final_column_names)

In [80]:
odf.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Education,Miscellaneous,Desired_Savings_Percentage,Desired_Savings,Disposable_Income,Saving_Rate,Total_Potential_Savings,Occupation_Retired,Occupation_Self_Employed,Occupation_Student
0,43033.009737,34,3,Student,1.0,8606.601947,0.0,1436.722787,5834.519895,3198.182773,...,3784.808282,1164.194464,14.341768,6171.69439,12123.213458,0.281719,2223.371129,0.0,0.0,1.0
1,11489.566457,19,4,Retired,0.0,3446.869937,2051.213623,410.251969,1685.074536,611.912676,...,588.817424,255.682115,7.287937,697.660941,697.660941,0.060721,831.7622,1.0,0.0,0.0
2,64302.916006,31,3,Self_Employed,0.0,19290.874802,0.0,1361.887366,8918.175983,5084.552672,...,3473.275105,1182.368354,14.716779,9463.317967,12213.291235,0.189934,2970.99787,0.0,1.0,0.0
3,5985.12004,35,3,Self_Employed,2.0,897.768006,308.373725,150.235396,620.098423,358.335042,...,472.610682,155.439767,6.922311,414.308638,1879.544464,0.314036,444.957861,0.0,1.0,0.0
4,11763.162384,60,1,Professional,1.0,2352.632477,0.0,325.799958,1757.571252,588.740982,...,1111.439149,255.292653,8.025482,944.050435,3331.198697,0.283189,927.862559,0.0,0.0,0.0

In [81]:
newodf = odf.drop('Occupation', axis=1)

In [82]:
newodf.head()

,Income,Age,Dependents,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,Eating_Out,...,Education,Miscellaneous,Desired_Savings_Percentage,Desired_Savings,Disposable_Income,Saving_Rate,Total_Potential_Savings,Occupation_Retired,Occupation_Self_Employed,Occupation_Student
0,43033.009737,34,3,1.0,8606.601947,0.0,1436.722787,5834.519895,3198.182773,1562.592315,...,3784.808282,1164.194464,14.341768,6171.69439,12123.213458,0.281719,2223.371129,0.0,0.0,1.0
1,11489.566457,19,4,0.0,3446.869937,2051.213623,410.251969,1685.074536,611.912676,382.739434,...,588.817424,255.682115,7.287937,697.660941,697.660941,0.060721,831.7622,1.0,0.0,0.0
2,64302.916006,31,3,0.0,19290.874802,0.0,1361.887366,8918.175983,5084.552672,2960.540197,...,3473.275105,1182.368354,14.716779,9463.317967,12213.291235,0.189934,2970.99787,0.0,1.0,0.0
3,5985.12004,35,3,2.0,897.768006,308.373725,150.235396,620.098423,358.335042,284.403056,...,472.610682,155.439767,6.922311,414.308638,1879.544464,0.314036,444.957861,0.0,1.0,0.0
4,11763.162384,60,1,1.0,2352.632477,0.0,325.799958,1757.571252,588.740982,248.124042,...,1111.439149,255.292653,8.025482,944.050435,3331.198697,0.283189,927.862559,0.0,0.0,0.0

In [83]:
newodf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Income                      16000 non-null  object
 1   Age                         16000 non-null  object
 2   Dependents                  16000 non-null  object
 3   City_Tier                   16000 non-null  object
 4   Rent                        16000 non-null  object
 5   Loan_Repayment              16000 non-null  object
 6   Insurance                   16000 non-null  object
 7   Groceries                   16000 non-null  object
 8   Transport                   16000 non-null  object
 9   Eating_Out                  16000 non-null  object
 10  Entertainment               16000 non-null  object
 11  Utilities                   16000 non-null  object
 12  Healthcare                  16000 non-null  object
 13  Education                   16000 non-null  object
 14  Miscellaneous               16000 non-null  object
 15  Desired_Savings_Percentage  16000 non-null  object
 16  Desired_Savings             16000 non-null  object
 17  Disposable_Income           16000 non-null  object
 18  Saving_Rate                 16000 non-null  object
 19  Total_Potential_Savings     16000 non-null  object
 20  Occupation_Retired          16000 non-null  object
 21  Occupation_Self_Employed    16000 non-null  object
 22  Occupation_Student          16000 non-null  object
dtypes: object(23)
memory usage: 2.8+ MB

In [25]:
scalar = StandardScaler()

In [85]:
scalar.fit(X_train_new)

StandardScaler()

In [86]:
X_train_scaled = scalar.transform(X_train_new)
X_test_scaled = scalar.transform(X_test_new)

In [89]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [91]:
# Predict on test data
y_pred = model.predict(X_test_scaled)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.81425
Confusion Matrix:
 [[   0  743]
 [   0 3257]]

In [97]:
model.predict(X_test_scaled[0].reshape(1, -1))

array([1])

In [100]:
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test_new)[:, 1]
roc_score = roc_auc_score(y_test, y_prob)
print("ROC AUC Score:", roc_score)

ROC AUC Score: 0.5023963295124572

In [99]:
X_test_scaled[0]

array([ 1.72429146, -0.57504086, -0.57600312])

#Bivariate Analysis

In [ ]:
plt.figure(figsize=(8,4))
sns.scatterplot(x = new_df['Income'], y = new_df['Age'], hue = new_df['Achieved_Goal'])
plt.ticklabel_format(style='plain', axis='x')
plt.xlabel('Income')
plt.ylabel('Age')
plt.title('Income vs Age')
plt.show()

In [ ]:
plt.figure(figsize=(4,4))
sns.boxplot(x= new_df['Income'], y= new_df['City_Tier'])
plt.xlabel('Income')
plt.ylabel('City Tier')
plt.title('Income vs City Tier')
plt.show()

In [ ]:
plt.figure(figsize=(6, 4))
sns.kdeplot(data=new_df, x='Income', hue='City_Tier', fill=True, alpha=0.2)
plt.xlabel('Income')
plt.title('Income Distribution by City Tier')
plt.show()